name: ${project.name}
version: ${project.version}
main: ${project.groupId}.Spawn
author: Jay
description: A lightweight and simple plugin for managing spawn locations and teleportation.

commands:
  spawn:
    description: Teleport to the spawn location.
    usage: /spawn [player]
  setspawn:
    description: Set the spawn location.
    usage: /setspawn
  reload:
    description: Reload the plugin configuration.
    usage: /spawn reload